###############################################################################
#
# Module:  lib Makefile
#
# Purpose: To manage project libraries
#
# Author:  Pete Nagy
#
###############################################################################

  SYSTEM = ../..
  MKINCLDIR = $(SYSTEM)/resource/mkinclude$(DEF_MKINCL)

#
# Include generic definitions
#

include $(MKINCLDIR)/generic

#
# List of managed subdirectories in dependency order
#

  MANAGED_DIRS = tess \
                 gv

#
# Include managed targets
#

include $(MKINCLDIR)/targets
