###############################################################################
#
# Module:  Makefile
#
# Purpose: To manage project programs
#
# Author:  Pete Nagy
#
###############################################################################

  SYSTEM = ../..
  MKINCLDIR = $(SYSTEM)/resource/mkinclude$(DEF_MKINCL)

#
# Include generic definitions
#

include $(MKINCLDIR)/generic

#
# List of managed subdirectories in dependency order
#

  MANAGED_DIRS = testmain

#
# Include managed targets
#

include $(MKINCLDIR)/targets
