################################################################################
#
# Module:  src Makefile
#
# Purpose: To manage project source build
#
# Author:  Pete Nagy
#
################################################################################

SYSTEM = ..
MKINCLDIR = $(SYSTEM)/resource/mkinclude$(DEF_MKINCL)

#
# Include defs for all makefiles
#

include $(MKINCLDIR)/generic

#
# List of managed subdirectories in dependency order
#

  MANAGED_DIRS = lib cc pymod

#
# Include managed targets
#

include $(MKINCLDIR)/targets
